FROM node:23.3.0-slim

WORKDIR /app

# Copy pre-built artifacts from GitHub Actions
COPY --chown=node:node . .

RUN ls -la

RUN ls -la packages/client

# Install runtime deps only
RUN apt-get update && \
    apt-get install -y git python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Use pre-built node_modules if exists
RUN if [ -d node_modules ]; then chown -R node:node node_modules; fi

USER node

CMD ["pnpm", "start:client"]