name: Build and Push

on:
  push:
    branches: [wau/develop, main]
    paths:
      - '**'
    #   - '!.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23.3.0'
      - run: npm install -g pnpm@latest
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            !**/node_modules/.cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - name: Build packages
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Create artifacts archive
        run: |
          mkdir -p .artifacts
          tar --use-compress-program='pigz --fast' \
            --exclude='node_modules/.cache' \
            -cf .artifacts/build-artifacts.tar.gz \
            app/build/ **/dist/ packages/**/lib/  **/node_modules/ \
            --ignore-failed-read

      - name: Upload artifacts archive
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: .artifacts/build-artifacts.tar.gz
          retention-days: 1

  docker-images:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [main, client]
    steps:
      - uses: actions/checkout@v4

      - name: Download and extract artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .artifacts

      - name: Extract artifacts
        run: |
          tar --use-compress-program='pigz -d' \
            -xf .artifacts/build-artifacts.tar.gz \
            -C $GITHUB_WORKSPACE

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          file: Dockerfile.${{ matrix.app }}
          push: true
          tags: |
            ghcr.io/${{ format(github.repository_owner) }}/eliza-${{ matrix.app }}:latest
            ghcr.io/${{ format(github.repository_owner) }}/eliza-${{ matrix.app }}:${{ github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false