name: Deploy to GCE

on:
  workflow_run:
    workflows: ["Build and Push"]
    types: [completed]
    branches: [wau/develop]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to GCE
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USER }}
        key: ${{ secrets.GCE_SSH_KEY }}
        script: |
          source ~/.bashrc
          export PATH="$HOME/.nvm/versions/node/v23.3.0/bin:$PATH"
          cd /var/www/eliza

          # copy docker-compose.demo.yml to /var/www/eliza/docker-compose.demo.yml
          cp docker-compose.demo.yml /var/www/eliza/docker-compose.demo.yml

          # copy scripts/deploy/deployment-demo.sh to /var/www/eliza/deployment-demo.sh
          cp scripts/deploy/deployment-demo.sh /var/www/eliza/deployment-demo.sh
          chmod +x /var/www/eliza/deployment-demo.sh

          # run the deployment script
          ./deployment-demo.sh
    env:
        GH_USER: ${{ github.actor }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}