name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches: [wau/develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: wau/develop

      # ... rest of the steps remain same ...